version: "3.8"

services:
  frontend:
    image: nginx:alpine
    container_name: spa_frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: >
      certonly --webroot
      --webroot-path=/var/lib/letsencrypt
      --email anderson.vida.digital@gmail.com
      --agree-tos
      --no-eff-email
      -d confimea-sanita.org
      -d www.confimea-sanita.org

volumes:
  certbot-etc:
  certbot-var:
